baseURL = 'https://www.abducovington.party'
languageCode = 'en-us'
title = 'Amina & Christian'
theme = 'Coder'

[params]
  customSCSS = ["scss/custom.scss"]

[markup.goldmark.renderer]
  unsafe = true

# [markup.goldmark.extensions.header]
#   anchor = false
